name: ci

on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11.0

      - run: make

      - name: Upload xmlcatalog.wasm
        uses: actions/upload-artifact@v4
        with:
          name: xmlcatalog.wasm
          path: xmlcatalog.wasm
          compression-level: 0
      - name: Upload xmllint.wasm
        uses: actions/upload-artifact@v4
        with:
          name: xmllint.wasm
          path: xmllint.wasm
          compression-level: 0
      - name: Upload xsltproc.wasm
        uses: actions/upload-artifact@v4
        with:
          name: xsltproc.wasm
          path: xsltproc.wasm
          compression-level: 0
